[package]
name = "protohackers"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "problem0"
path = "src/problem0.rs"

[[bin]]
name = "problem1"
path = "src/problem1.rs"

[dependencies]
serde = "1.0.219"
serde_json = "1.0.142"
serde_valid = "1.0.5"
